### ISSUE TITLE
Gnax - vielleicht is jetzt bessa..

### ISSUE THREAD

**Issue by robertaistleitner** [grexi/issuetestix#4]
**Sender**: ra@usersnap.com
**Notes**:
- vielleicht is jetzt bessa..

![Gnax - vielleicht is jetzt bessa..](https://usersnappublic.s3.amazonaws.com/2014-03-25/15-25/0e1d7ed9-46b2-4ce9-8ff4-890d6e010ee1.png)

**Browser**: Chrome 33 (Linux)
**Referer**: [http://orf.at/](http://orf.at/)
**IP**: 192.168.10.245

---

Powered by [http://usersnap.com](http://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by grexi** [comment]
I can reply here that's great
